# docker-compose.yml

version: '3'
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: ovecell_db
      POSTGRES_USER: ovecell_user
      POSTGRES_PASSWORD: ovecell_password
    ports:
      - "5432:5432"
  app:
    build: .
    command: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - database
